# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Michel Lacerda
email: michellacerdasilva@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
# Highlighter
# highlighter: pygments

# Social Media
twitter_username: michel_lacerda_
github_username:  MichelLacerda

# Markdown
markdown: kramdown

# Other settings
exclude: ['README.md', 'LICENSE']

# i18n and encode
timezone: America/Sao_Paulo
encoding: utf-8

# urlpatterns
permalink: /post/:title
# baseurl: "/gd"
url: "http://michellacerda.com.br"
static: /static/
# media: /gd/media/
# post_image: /gd/media/post/images/
# post_thumb: /gd/media/post/thumbnail/
# favicon: /gd/media/favicon.png

# Post
gems: [jekyll-paginate]
post_total: False
paginate: 1
paginate_path: "/posts/:num"
thumb_width: 390px
thumb_height: 300px